version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - /var/nginx/html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
